# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wesley/src/dec

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wesley/src/dec

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wesley/src/dec/CMakeFiles /home/wesley/src/dec/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wesley/src/dec/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named memoize

# Build rule for target.
memoize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memoize
.PHONY : memoize

# fast build rule for target.
memoize/fast:
	$(MAKE) -f CMakeFiles/memoize.dir/build.make CMakeFiles/memoize.dir/build
.PHONY : memoize/fast

#=============================================================================
# Target rules for targets named log

# Build rule for target.
log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log
.PHONY : log

# fast build rule for target.
log/fast:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/build
.PHONY : log/fast

#=============================================================================
# Target rules for targets named atomic

# Build rule for target.
atomic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atomic
.PHONY : atomic

# fast build rule for target.
atomic/fast:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/build
.PHONY : atomic/fast

src/example_atomic.o: src/example_atomic.cpp.o

.PHONY : src/example_atomic.o

# target to build an object file
src/example_atomic.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/example_atomic.cpp.o
.PHONY : src/example_atomic.cpp.o

src/example_atomic.i: src/example_atomic.cpp.i

.PHONY : src/example_atomic.i

# target to preprocess a source file
src/example_atomic.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/example_atomic.cpp.i
.PHONY : src/example_atomic.cpp.i

src/example_atomic.s: src/example_atomic.cpp.s

.PHONY : src/example_atomic.s

# target to generate assembly for a file
src/example_atomic.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/example_atomic.cpp.s
.PHONY : src/example_atomic.cpp.s

src/example_log.o: src/example_log.cpp.o

.PHONY : src/example_log.o

# target to build an object file
src/example_log.cpp.o:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/src/example_log.cpp.o
.PHONY : src/example_log.cpp.o

src/example_log.i: src/example_log.cpp.i

.PHONY : src/example_log.i

# target to preprocess a source file
src/example_log.cpp.i:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/src/example_log.cpp.i
.PHONY : src/example_log.cpp.i

src/example_log.s: src/example_log.cpp.s

.PHONY : src/example_log.s

# target to generate assembly for a file
src/example_log.cpp.s:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/src/example_log.cpp.s
.PHONY : src/example_log.cpp.s

src/example_memoize.o: src/example_memoize.cpp.o

.PHONY : src/example_memoize.o

# target to build an object file
src/example_memoize.cpp.o:
	$(MAKE) -f CMakeFiles/memoize.dir/build.make CMakeFiles/memoize.dir/src/example_memoize.cpp.o
.PHONY : src/example_memoize.cpp.o

src/example_memoize.i: src/example_memoize.cpp.i

.PHONY : src/example_memoize.i

# target to preprocess a source file
src/example_memoize.cpp.i:
	$(MAKE) -f CMakeFiles/memoize.dir/build.make CMakeFiles/memoize.dir/src/example_memoize.cpp.i
.PHONY : src/example_memoize.cpp.i

src/example_memoize.s: src/example_memoize.cpp.s

.PHONY : src/example_memoize.s

# target to generate assembly for a file
src/example_memoize.cpp.s:
	$(MAKE) -f CMakeFiles/memoize.dir/build.make CMakeFiles/memoize.dir/src/example_memoize.cpp.s
.PHONY : src/example_memoize.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... memoize"
	@echo "... edit_cache"
	@echo "... log"
	@echo "... atomic"
	@echo "... rebuild_cache"
	@echo "... src/example_atomic.o"
	@echo "... src/example_atomic.i"
	@echo "... src/example_atomic.s"
	@echo "... src/example_log.o"
	@echo "... src/example_log.i"
	@echo "... src/example_log.s"
	@echo "... src/example_memoize.o"
	@echo "... src/example_memoize.i"
	@echo "... src/example_memoize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

